services:
  jaProxy-httpd:
    build:
      context: .
    container_name: jaProxy_httpd
    image: japroxy-httpd:latest
    networks:
      - proxy-inet
    ports:
      - '3000:3000'
    restart: unless-stopped

networks:
  proxy-inet:
    driver: bridge
    name: proxy_inet
