services:
  jaProxy-httpd:
    build:
      context: .
    container_name: jaProxy_httpd
    # env_file: .env
    image: japroxy-httpd:latest
    ports:
      - '3000:3000'
    restart: unless-stopped
