
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/GlobalUserLicense.js'
export type * from './models/GlobalGroupLicense.js'
export type * from './models/Product.js'
export type * from './models/UserLicense.js'
export type * from './models/GroupLicense.js'
export type * from './commonInputTypes.js'