
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  GlobalUserLicense: 'GlobalUserLicense',
  GlobalGroupLicense: 'GlobalGroupLicense',
  Product: 'Product',
  UserLicense: 'UserLicense',
  GroupLicense: 'GroupLicense'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const GlobalUserLicenseScalarFieldEnum = {
  id: 'id',
  robloxUserId: 'robloxUserId',
  accessType: 'accessType',
  reason: 'reason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GlobalUserLicenseScalarFieldEnum = (typeof GlobalUserLicenseScalarFieldEnum)[keyof typeof GlobalUserLicenseScalarFieldEnum]


export const GlobalGroupLicenseScalarFieldEnum = {
  id: 'id',
  robloxGroupId: 'robloxGroupId',
  accessType: 'accessType',
  reason: 'reason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GlobalGroupLicenseScalarFieldEnum = (typeof GlobalGroupLicenseScalarFieldEnum)[keyof typeof GlobalGroupLicenseScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const UserLicenseScalarFieldEnum = {
  id: 'id',
  robloxUserId: 'robloxUserId',
  productId: 'productId',
  accessType: 'accessType',
  reason: 'reason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserLicenseScalarFieldEnum = (typeof UserLicenseScalarFieldEnum)[keyof typeof UserLicenseScalarFieldEnum]


export const GroupLicenseScalarFieldEnum = {
  id: 'id',
  robloxGroupId: 'robloxGroupId',
  productId: 'productId',
  accessType: 'accessType',
  reason: 'reason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GroupLicenseScalarFieldEnum = (typeof GroupLicenseScalarFieldEnum)[keyof typeof GroupLicenseScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const GlobalUserLicenseOrderByRelevanceFieldEnum = {
  id: 'id',
  reason: 'reason'
} as const

export type GlobalUserLicenseOrderByRelevanceFieldEnum = (typeof GlobalUserLicenseOrderByRelevanceFieldEnum)[keyof typeof GlobalUserLicenseOrderByRelevanceFieldEnum]


export const GlobalGroupLicenseOrderByRelevanceFieldEnum = {
  id: 'id',
  reason: 'reason'
} as const

export type GlobalGroupLicenseOrderByRelevanceFieldEnum = (typeof GlobalGroupLicenseOrderByRelevanceFieldEnum)[keyof typeof GlobalGroupLicenseOrderByRelevanceFieldEnum]


export const ProductOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type ProductOrderByRelevanceFieldEnum = (typeof ProductOrderByRelevanceFieldEnum)[keyof typeof ProductOrderByRelevanceFieldEnum]


export const UserLicenseOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  reason: 'reason'
} as const

export type UserLicenseOrderByRelevanceFieldEnum = (typeof UserLicenseOrderByRelevanceFieldEnum)[keyof typeof UserLicenseOrderByRelevanceFieldEnum]


export const GroupLicenseOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  reason: 'reason'
} as const

export type GroupLicenseOrderByRelevanceFieldEnum = (typeof GroupLicenseOrderByRelevanceFieldEnum)[keyof typeof GroupLicenseOrderByRelevanceFieldEnum]

