
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GlobalUserLicense` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GlobalUserLicense
 * 
 */
export type GlobalUserLicenseModel = runtime.Types.Result.DefaultSelection<Prisma.$GlobalUserLicensePayload>

export type AggregateGlobalUserLicense = {
  _count: GlobalUserLicenseCountAggregateOutputType | null
  _avg: GlobalUserLicenseAvgAggregateOutputType | null
  _sum: GlobalUserLicenseSumAggregateOutputType | null
  _min: GlobalUserLicenseMinAggregateOutputType | null
  _max: GlobalUserLicenseMaxAggregateOutputType | null
}

export type GlobalUserLicenseAvgAggregateOutputType = {
  robloxUserId: number | null
}

export type GlobalUserLicenseSumAggregateOutputType = {
  robloxUserId: bigint | null
}

export type GlobalUserLicenseMinAggregateOutputType = {
  id: string | null
  robloxUserId: bigint | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GlobalUserLicenseMaxAggregateOutputType = {
  id: string | null
  robloxUserId: bigint | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GlobalUserLicenseCountAggregateOutputType = {
  id: number
  robloxUserId: number
  accessType: number
  reason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GlobalUserLicenseAvgAggregateInputType = {
  robloxUserId?: true
}

export type GlobalUserLicenseSumAggregateInputType = {
  robloxUserId?: true
}

export type GlobalUserLicenseMinAggregateInputType = {
  id?: true
  robloxUserId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type GlobalUserLicenseMaxAggregateInputType = {
  id?: true
  robloxUserId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type GlobalUserLicenseCountAggregateInputType = {
  id?: true
  robloxUserId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GlobalUserLicenseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalUserLicense to aggregate.
   */
  where?: Prisma.GlobalUserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalUserLicenses to fetch.
   */
  orderBy?: Prisma.GlobalUserLicenseOrderByWithRelationInput | Prisma.GlobalUserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GlobalUserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalUserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalUserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GlobalUserLicenses
  **/
  _count?: true | GlobalUserLicenseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GlobalUserLicenseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GlobalUserLicenseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GlobalUserLicenseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GlobalUserLicenseMaxAggregateInputType
}

export type GetGlobalUserLicenseAggregateType<T extends GlobalUserLicenseAggregateArgs> = {
      [P in keyof T & keyof AggregateGlobalUserLicense]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGlobalUserLicense[P]>
    : Prisma.GetScalarType<T[P], AggregateGlobalUserLicense[P]>
}




export type GlobalUserLicenseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GlobalUserLicenseWhereInput
  orderBy?: Prisma.GlobalUserLicenseOrderByWithAggregationInput | Prisma.GlobalUserLicenseOrderByWithAggregationInput[]
  by: Prisma.GlobalUserLicenseScalarFieldEnum[] | Prisma.GlobalUserLicenseScalarFieldEnum
  having?: Prisma.GlobalUserLicenseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GlobalUserLicenseCountAggregateInputType | true
  _avg?: GlobalUserLicenseAvgAggregateInputType
  _sum?: GlobalUserLicenseSumAggregateInputType
  _min?: GlobalUserLicenseMinAggregateInputType
  _max?: GlobalUserLicenseMaxAggregateInputType
}

export type GlobalUserLicenseGroupByOutputType = {
  id: string
  robloxUserId: bigint
  accessType: $Enums.AccessType
  reason: string | null
  createdAt: Date
  updatedAt: Date
  _count: GlobalUserLicenseCountAggregateOutputType | null
  _avg: GlobalUserLicenseAvgAggregateOutputType | null
  _sum: GlobalUserLicenseSumAggregateOutputType | null
  _min: GlobalUserLicenseMinAggregateOutputType | null
  _max: GlobalUserLicenseMaxAggregateOutputType | null
}

export type GetGlobalUserLicenseGroupByPayload<T extends GlobalUserLicenseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GlobalUserLicenseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GlobalUserLicenseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GlobalUserLicenseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GlobalUserLicenseGroupByOutputType[P]>
      }
    >
  >



export type GlobalUserLicenseWhereInput = {
  AND?: Prisma.GlobalUserLicenseWhereInput | Prisma.GlobalUserLicenseWhereInput[]
  OR?: Prisma.GlobalUserLicenseWhereInput[]
  NOT?: Prisma.GlobalUserLicenseWhereInput | Prisma.GlobalUserLicenseWhereInput[]
  id?: Prisma.StringFilter<"GlobalUserLicense"> | string
  robloxUserId?: Prisma.BigIntFilter<"GlobalUserLicense"> | bigint | number
  accessType?: Prisma.EnumAccessTypeFilter<"GlobalUserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GlobalUserLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GlobalUserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GlobalUserLicense"> | Date | string
}

export type GlobalUserLicenseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.GlobalUserLicenseOrderByRelevanceInput
}

export type GlobalUserLicenseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  robloxUserId?: bigint | number
  AND?: Prisma.GlobalUserLicenseWhereInput | Prisma.GlobalUserLicenseWhereInput[]
  OR?: Prisma.GlobalUserLicenseWhereInput[]
  NOT?: Prisma.GlobalUserLicenseWhereInput | Prisma.GlobalUserLicenseWhereInput[]
  accessType?: Prisma.EnumAccessTypeFilter<"GlobalUserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GlobalUserLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GlobalUserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GlobalUserLicense"> | Date | string
}, "id" | "robloxUserId">

export type GlobalUserLicenseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GlobalUserLicenseCountOrderByAggregateInput
  _avg?: Prisma.GlobalUserLicenseAvgOrderByAggregateInput
  _max?: Prisma.GlobalUserLicenseMaxOrderByAggregateInput
  _min?: Prisma.GlobalUserLicenseMinOrderByAggregateInput
  _sum?: Prisma.GlobalUserLicenseSumOrderByAggregateInput
}

export type GlobalUserLicenseScalarWhereWithAggregatesInput = {
  AND?: Prisma.GlobalUserLicenseScalarWhereWithAggregatesInput | Prisma.GlobalUserLicenseScalarWhereWithAggregatesInput[]
  OR?: Prisma.GlobalUserLicenseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GlobalUserLicenseScalarWhereWithAggregatesInput | Prisma.GlobalUserLicenseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GlobalUserLicense"> | string
  robloxUserId?: Prisma.BigIntWithAggregatesFilter<"GlobalUserLicense"> | bigint | number
  accessType?: Prisma.EnumAccessTypeWithAggregatesFilter<"GlobalUserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableWithAggregatesFilter<"GlobalUserLicense"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalUserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalUserLicense"> | Date | string
}

export type GlobalUserLicenseCreateInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalUserLicenseUncheckedCreateInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalUserLicenseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalUserLicenseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalUserLicenseCreateManyInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalUserLicenseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalUserLicenseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalUserLicenseOrderByRelevanceInput = {
  fields: Prisma.GlobalUserLicenseOrderByRelevanceFieldEnum | Prisma.GlobalUserLicenseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type GlobalUserLicenseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalUserLicenseAvgOrderByAggregateInput = {
  robloxUserId?: Prisma.SortOrder
}

export type GlobalUserLicenseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalUserLicenseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalUserLicenseSumOrderByAggregateInput = {
  robloxUserId?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type EnumAccessTypeFieldUpdateOperationsInput = {
  set?: $Enums.AccessType
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type GlobalUserLicenseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  robloxUserId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalUserLicense"]>



export type GlobalUserLicenseSelectScalar = {
  id?: boolean
  robloxUserId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GlobalUserLicenseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "robloxUserId" | "accessType" | "reason" | "createdAt" | "updatedAt", ExtArgs["result"]["globalUserLicense"]>

export type $GlobalUserLicensePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GlobalUserLicense"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    robloxUserId: bigint
    accessType: $Enums.AccessType
    reason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["globalUserLicense"]>
  composites: {}
}

export type GlobalUserLicenseGetPayload<S extends boolean | null | undefined | GlobalUserLicenseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload, S>

export type GlobalUserLicenseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GlobalUserLicenseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GlobalUserLicenseCountAggregateInputType | true
  }

export interface GlobalUserLicenseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GlobalUserLicense'], meta: { name: 'GlobalUserLicense' } }
  /**
   * Find zero or one GlobalUserLicense that matches the filter.
   * @param {GlobalUserLicenseFindUniqueArgs} args - Arguments to find a GlobalUserLicense
   * @example
   * // Get one GlobalUserLicense
   * const globalUserLicense = await prisma.globalUserLicense.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GlobalUserLicenseFindUniqueArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GlobalUserLicense that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GlobalUserLicenseFindUniqueOrThrowArgs} args - Arguments to find a GlobalUserLicense
   * @example
   * // Get one GlobalUserLicense
   * const globalUserLicense = await prisma.globalUserLicense.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GlobalUserLicenseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalUserLicense that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseFindFirstArgs} args - Arguments to find a GlobalUserLicense
   * @example
   * // Get one GlobalUserLicense
   * const globalUserLicense = await prisma.globalUserLicense.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GlobalUserLicenseFindFirstArgs>(args?: Prisma.SelectSubset<T, GlobalUserLicenseFindFirstArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalUserLicense that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseFindFirstOrThrowArgs} args - Arguments to find a GlobalUserLicense
   * @example
   * // Get one GlobalUserLicense
   * const globalUserLicense = await prisma.globalUserLicense.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GlobalUserLicenseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GlobalUserLicenseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GlobalUserLicenses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GlobalUserLicenses
   * const globalUserLicenses = await prisma.globalUserLicense.findMany()
   * 
   * // Get first 10 GlobalUserLicenses
   * const globalUserLicenses = await prisma.globalUserLicense.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const globalUserLicenseWithIdOnly = await prisma.globalUserLicense.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GlobalUserLicenseFindManyArgs>(args?: Prisma.SelectSubset<T, GlobalUserLicenseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GlobalUserLicense.
   * @param {GlobalUserLicenseCreateArgs} args - Arguments to create a GlobalUserLicense.
   * @example
   * // Create one GlobalUserLicense
   * const GlobalUserLicense = await prisma.globalUserLicense.create({
   *   data: {
   *     // ... data to create a GlobalUserLicense
   *   }
   * })
   * 
   */
  create<T extends GlobalUserLicenseCreateArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseCreateArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GlobalUserLicenses.
   * @param {GlobalUserLicenseCreateManyArgs} args - Arguments to create many GlobalUserLicenses.
   * @example
   * // Create many GlobalUserLicenses
   * const globalUserLicense = await prisma.globalUserLicense.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GlobalUserLicenseCreateManyArgs>(args?: Prisma.SelectSubset<T, GlobalUserLicenseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a GlobalUserLicense.
   * @param {GlobalUserLicenseDeleteArgs} args - Arguments to delete one GlobalUserLicense.
   * @example
   * // Delete one GlobalUserLicense
   * const GlobalUserLicense = await prisma.globalUserLicense.delete({
   *   where: {
   *     // ... filter to delete one GlobalUserLicense
   *   }
   * })
   * 
   */
  delete<T extends GlobalUserLicenseDeleteArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseDeleteArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GlobalUserLicense.
   * @param {GlobalUserLicenseUpdateArgs} args - Arguments to update one GlobalUserLicense.
   * @example
   * // Update one GlobalUserLicense
   * const globalUserLicense = await prisma.globalUserLicense.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GlobalUserLicenseUpdateArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseUpdateArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GlobalUserLicenses.
   * @param {GlobalUserLicenseDeleteManyArgs} args - Arguments to filter GlobalUserLicenses to delete.
   * @example
   * // Delete a few GlobalUserLicenses
   * const { count } = await prisma.globalUserLicense.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GlobalUserLicenseDeleteManyArgs>(args?: Prisma.SelectSubset<T, GlobalUserLicenseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GlobalUserLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GlobalUserLicenses
   * const globalUserLicense = await prisma.globalUserLicense.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GlobalUserLicenseUpdateManyArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one GlobalUserLicense.
   * @param {GlobalUserLicenseUpsertArgs} args - Arguments to update or create a GlobalUserLicense.
   * @example
   * // Update or create a GlobalUserLicense
   * const globalUserLicense = await prisma.globalUserLicense.upsert({
   *   create: {
   *     // ... data to create a GlobalUserLicense
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GlobalUserLicense we want to update
   *   }
   * })
   */
  upsert<T extends GlobalUserLicenseUpsertArgs>(args: Prisma.SelectSubset<T, GlobalUserLicenseUpsertArgs<ExtArgs>>): Prisma.Prisma__GlobalUserLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalUserLicensePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GlobalUserLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseCountArgs} args - Arguments to filter GlobalUserLicenses to count.
   * @example
   * // Count the number of GlobalUserLicenses
   * const count = await prisma.globalUserLicense.count({
   *   where: {
   *     // ... the filter for the GlobalUserLicenses we want to count
   *   }
   * })
  **/
  count<T extends GlobalUserLicenseCountArgs>(
    args?: Prisma.Subset<T, GlobalUserLicenseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GlobalUserLicenseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GlobalUserLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GlobalUserLicenseAggregateArgs>(args: Prisma.Subset<T, GlobalUserLicenseAggregateArgs>): Prisma.PrismaPromise<GetGlobalUserLicenseAggregateType<T>>

  /**
   * Group by GlobalUserLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalUserLicenseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GlobalUserLicenseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GlobalUserLicenseGroupByArgs['orderBy'] }
      : { orderBy?: GlobalUserLicenseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GlobalUserLicenseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGlobalUserLicenseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GlobalUserLicense model
 */
readonly fields: GlobalUserLicenseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GlobalUserLicense.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GlobalUserLicenseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GlobalUserLicense model
 */
export interface GlobalUserLicenseFieldRefs {
  readonly id: Prisma.FieldRef<"GlobalUserLicense", 'String'>
  readonly robloxUserId: Prisma.FieldRef<"GlobalUserLicense", 'BigInt'>
  readonly accessType: Prisma.FieldRef<"GlobalUserLicense", 'AccessType'>
  readonly reason: Prisma.FieldRef<"GlobalUserLicense", 'String'>
  readonly createdAt: Prisma.FieldRef<"GlobalUserLicense", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GlobalUserLicense", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GlobalUserLicense findUnique
 */
export type GlobalUserLicenseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalUserLicense to fetch.
   */
  where: Prisma.GlobalUserLicenseWhereUniqueInput
}

/**
 * GlobalUserLicense findUniqueOrThrow
 */
export type GlobalUserLicenseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalUserLicense to fetch.
   */
  where: Prisma.GlobalUserLicenseWhereUniqueInput
}

/**
 * GlobalUserLicense findFirst
 */
export type GlobalUserLicenseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalUserLicense to fetch.
   */
  where?: Prisma.GlobalUserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalUserLicenses to fetch.
   */
  orderBy?: Prisma.GlobalUserLicenseOrderByWithRelationInput | Prisma.GlobalUserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalUserLicenses.
   */
  cursor?: Prisma.GlobalUserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalUserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalUserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalUserLicenses.
   */
  distinct?: Prisma.GlobalUserLicenseScalarFieldEnum | Prisma.GlobalUserLicenseScalarFieldEnum[]
}

/**
 * GlobalUserLicense findFirstOrThrow
 */
export type GlobalUserLicenseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalUserLicense to fetch.
   */
  where?: Prisma.GlobalUserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalUserLicenses to fetch.
   */
  orderBy?: Prisma.GlobalUserLicenseOrderByWithRelationInput | Prisma.GlobalUserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalUserLicenses.
   */
  cursor?: Prisma.GlobalUserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalUserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalUserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalUserLicenses.
   */
  distinct?: Prisma.GlobalUserLicenseScalarFieldEnum | Prisma.GlobalUserLicenseScalarFieldEnum[]
}

/**
 * GlobalUserLicense findMany
 */
export type GlobalUserLicenseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalUserLicenses to fetch.
   */
  where?: Prisma.GlobalUserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalUserLicenses to fetch.
   */
  orderBy?: Prisma.GlobalUserLicenseOrderByWithRelationInput | Prisma.GlobalUserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GlobalUserLicenses.
   */
  cursor?: Prisma.GlobalUserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalUserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalUserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalUserLicenses.
   */
  distinct?: Prisma.GlobalUserLicenseScalarFieldEnum | Prisma.GlobalUserLicenseScalarFieldEnum[]
}

/**
 * GlobalUserLicense create
 */
export type GlobalUserLicenseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * The data needed to create a GlobalUserLicense.
   */
  data: Prisma.XOR<Prisma.GlobalUserLicenseCreateInput, Prisma.GlobalUserLicenseUncheckedCreateInput>
}

/**
 * GlobalUserLicense createMany
 */
export type GlobalUserLicenseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GlobalUserLicenses.
   */
  data: Prisma.GlobalUserLicenseCreateManyInput | Prisma.GlobalUserLicenseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GlobalUserLicense update
 */
export type GlobalUserLicenseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * The data needed to update a GlobalUserLicense.
   */
  data: Prisma.XOR<Prisma.GlobalUserLicenseUpdateInput, Prisma.GlobalUserLicenseUncheckedUpdateInput>
  /**
   * Choose, which GlobalUserLicense to update.
   */
  where: Prisma.GlobalUserLicenseWhereUniqueInput
}

/**
 * GlobalUserLicense updateMany
 */
export type GlobalUserLicenseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GlobalUserLicenses.
   */
  data: Prisma.XOR<Prisma.GlobalUserLicenseUpdateManyMutationInput, Prisma.GlobalUserLicenseUncheckedUpdateManyInput>
  /**
   * Filter which GlobalUserLicenses to update
   */
  where?: Prisma.GlobalUserLicenseWhereInput
  /**
   * Limit how many GlobalUserLicenses to update.
   */
  limit?: number
}

/**
 * GlobalUserLicense upsert
 */
export type GlobalUserLicenseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * The filter to search for the GlobalUserLicense to update in case it exists.
   */
  where: Prisma.GlobalUserLicenseWhereUniqueInput
  /**
   * In case the GlobalUserLicense found by the `where` argument doesn't exist, create a new GlobalUserLicense with this data.
   */
  create: Prisma.XOR<Prisma.GlobalUserLicenseCreateInput, Prisma.GlobalUserLicenseUncheckedCreateInput>
  /**
   * In case the GlobalUserLicense was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GlobalUserLicenseUpdateInput, Prisma.GlobalUserLicenseUncheckedUpdateInput>
}

/**
 * GlobalUserLicense delete
 */
export type GlobalUserLicenseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
  /**
   * Filter which GlobalUserLicense to delete.
   */
  where: Prisma.GlobalUserLicenseWhereUniqueInput
}

/**
 * GlobalUserLicense deleteMany
 */
export type GlobalUserLicenseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalUserLicenses to delete
   */
  where?: Prisma.GlobalUserLicenseWhereInput
  /**
   * Limit how many GlobalUserLicenses to delete.
   */
  limit?: number
}

/**
 * GlobalUserLicense without action
 */
export type GlobalUserLicenseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalUserLicense
   */
  select?: Prisma.GlobalUserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalUserLicense
   */
  omit?: Prisma.GlobalUserLicenseOmit<ExtArgs> | null
}
