
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GlobalGroupLicense` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GlobalGroupLicense
 * 
 */
export type GlobalGroupLicenseModel = runtime.Types.Result.DefaultSelection<Prisma.$GlobalGroupLicensePayload>

export type AggregateGlobalGroupLicense = {
  _count: GlobalGroupLicenseCountAggregateOutputType | null
  _avg: GlobalGroupLicenseAvgAggregateOutputType | null
  _sum: GlobalGroupLicenseSumAggregateOutputType | null
  _min: GlobalGroupLicenseMinAggregateOutputType | null
  _max: GlobalGroupLicenseMaxAggregateOutputType | null
}

export type GlobalGroupLicenseAvgAggregateOutputType = {
  robloxGroupId: number | null
}

export type GlobalGroupLicenseSumAggregateOutputType = {
  robloxGroupId: bigint | null
}

export type GlobalGroupLicenseMinAggregateOutputType = {
  id: string | null
  robloxGroupId: bigint | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GlobalGroupLicenseMaxAggregateOutputType = {
  id: string | null
  robloxGroupId: bigint | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GlobalGroupLicenseCountAggregateOutputType = {
  id: number
  robloxGroupId: number
  accessType: number
  reason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GlobalGroupLicenseAvgAggregateInputType = {
  robloxGroupId?: true
}

export type GlobalGroupLicenseSumAggregateInputType = {
  robloxGroupId?: true
}

export type GlobalGroupLicenseMinAggregateInputType = {
  id?: true
  robloxGroupId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type GlobalGroupLicenseMaxAggregateInputType = {
  id?: true
  robloxGroupId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type GlobalGroupLicenseCountAggregateInputType = {
  id?: true
  robloxGroupId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GlobalGroupLicenseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalGroupLicense to aggregate.
   */
  where?: Prisma.GlobalGroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalGroupLicenses to fetch.
   */
  orderBy?: Prisma.GlobalGroupLicenseOrderByWithRelationInput | Prisma.GlobalGroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GlobalGroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalGroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalGroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GlobalGroupLicenses
  **/
  _count?: true | GlobalGroupLicenseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GlobalGroupLicenseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GlobalGroupLicenseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GlobalGroupLicenseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GlobalGroupLicenseMaxAggregateInputType
}

export type GetGlobalGroupLicenseAggregateType<T extends GlobalGroupLicenseAggregateArgs> = {
      [P in keyof T & keyof AggregateGlobalGroupLicense]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGlobalGroupLicense[P]>
    : Prisma.GetScalarType<T[P], AggregateGlobalGroupLicense[P]>
}




export type GlobalGroupLicenseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GlobalGroupLicenseWhereInput
  orderBy?: Prisma.GlobalGroupLicenseOrderByWithAggregationInput | Prisma.GlobalGroupLicenseOrderByWithAggregationInput[]
  by: Prisma.GlobalGroupLicenseScalarFieldEnum[] | Prisma.GlobalGroupLicenseScalarFieldEnum
  having?: Prisma.GlobalGroupLicenseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GlobalGroupLicenseCountAggregateInputType | true
  _avg?: GlobalGroupLicenseAvgAggregateInputType
  _sum?: GlobalGroupLicenseSumAggregateInputType
  _min?: GlobalGroupLicenseMinAggregateInputType
  _max?: GlobalGroupLicenseMaxAggregateInputType
}

export type GlobalGroupLicenseGroupByOutputType = {
  id: string
  robloxGroupId: bigint
  accessType: $Enums.AccessType
  reason: string | null
  createdAt: Date
  updatedAt: Date
  _count: GlobalGroupLicenseCountAggregateOutputType | null
  _avg: GlobalGroupLicenseAvgAggregateOutputType | null
  _sum: GlobalGroupLicenseSumAggregateOutputType | null
  _min: GlobalGroupLicenseMinAggregateOutputType | null
  _max: GlobalGroupLicenseMaxAggregateOutputType | null
}

export type GetGlobalGroupLicenseGroupByPayload<T extends GlobalGroupLicenseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GlobalGroupLicenseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GlobalGroupLicenseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GlobalGroupLicenseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GlobalGroupLicenseGroupByOutputType[P]>
      }
    >
  >



export type GlobalGroupLicenseWhereInput = {
  AND?: Prisma.GlobalGroupLicenseWhereInput | Prisma.GlobalGroupLicenseWhereInput[]
  OR?: Prisma.GlobalGroupLicenseWhereInput[]
  NOT?: Prisma.GlobalGroupLicenseWhereInput | Prisma.GlobalGroupLicenseWhereInput[]
  id?: Prisma.StringFilter<"GlobalGroupLicense"> | string
  robloxGroupId?: Prisma.BigIntFilter<"GlobalGroupLicense"> | bigint | number
  accessType?: Prisma.EnumAccessTypeFilter<"GlobalGroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GlobalGroupLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GlobalGroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GlobalGroupLicense"> | Date | string
}

export type GlobalGroupLicenseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.GlobalGroupLicenseOrderByRelevanceInput
}

export type GlobalGroupLicenseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  robloxGroupId?: bigint | number
  AND?: Prisma.GlobalGroupLicenseWhereInput | Prisma.GlobalGroupLicenseWhereInput[]
  OR?: Prisma.GlobalGroupLicenseWhereInput[]
  NOT?: Prisma.GlobalGroupLicenseWhereInput | Prisma.GlobalGroupLicenseWhereInput[]
  accessType?: Prisma.EnumAccessTypeFilter<"GlobalGroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GlobalGroupLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GlobalGroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GlobalGroupLicense"> | Date | string
}, "id" | "robloxGroupId">

export type GlobalGroupLicenseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GlobalGroupLicenseCountOrderByAggregateInput
  _avg?: Prisma.GlobalGroupLicenseAvgOrderByAggregateInput
  _max?: Prisma.GlobalGroupLicenseMaxOrderByAggregateInput
  _min?: Prisma.GlobalGroupLicenseMinOrderByAggregateInput
  _sum?: Prisma.GlobalGroupLicenseSumOrderByAggregateInput
}

export type GlobalGroupLicenseScalarWhereWithAggregatesInput = {
  AND?: Prisma.GlobalGroupLicenseScalarWhereWithAggregatesInput | Prisma.GlobalGroupLicenseScalarWhereWithAggregatesInput[]
  OR?: Prisma.GlobalGroupLicenseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GlobalGroupLicenseScalarWhereWithAggregatesInput | Prisma.GlobalGroupLicenseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GlobalGroupLicense"> | string
  robloxGroupId?: Prisma.BigIntWithAggregatesFilter<"GlobalGroupLicense"> | bigint | number
  accessType?: Prisma.EnumAccessTypeWithAggregatesFilter<"GlobalGroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableWithAggregatesFilter<"GlobalGroupLicense"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalGroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalGroupLicense"> | Date | string
}

export type GlobalGroupLicenseCreateInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalGroupLicenseUncheckedCreateInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalGroupLicenseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalGroupLicenseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalGroupLicenseCreateManyInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalGroupLicenseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalGroupLicenseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalGroupLicenseOrderByRelevanceInput = {
  fields: Prisma.GlobalGroupLicenseOrderByRelevanceFieldEnum | Prisma.GlobalGroupLicenseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type GlobalGroupLicenseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalGroupLicenseAvgOrderByAggregateInput = {
  robloxGroupId?: Prisma.SortOrder
}

export type GlobalGroupLicenseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalGroupLicenseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalGroupLicenseSumOrderByAggregateInput = {
  robloxGroupId?: Prisma.SortOrder
}



export type GlobalGroupLicenseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  robloxGroupId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalGroupLicense"]>



export type GlobalGroupLicenseSelectScalar = {
  id?: boolean
  robloxGroupId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GlobalGroupLicenseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "robloxGroupId" | "accessType" | "reason" | "createdAt" | "updatedAt", ExtArgs["result"]["globalGroupLicense"]>

export type $GlobalGroupLicensePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GlobalGroupLicense"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    robloxGroupId: bigint
    accessType: $Enums.AccessType
    reason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["globalGroupLicense"]>
  composites: {}
}

export type GlobalGroupLicenseGetPayload<S extends boolean | null | undefined | GlobalGroupLicenseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload, S>

export type GlobalGroupLicenseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GlobalGroupLicenseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GlobalGroupLicenseCountAggregateInputType | true
  }

export interface GlobalGroupLicenseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GlobalGroupLicense'], meta: { name: 'GlobalGroupLicense' } }
  /**
   * Find zero or one GlobalGroupLicense that matches the filter.
   * @param {GlobalGroupLicenseFindUniqueArgs} args - Arguments to find a GlobalGroupLicense
   * @example
   * // Get one GlobalGroupLicense
   * const globalGroupLicense = await prisma.globalGroupLicense.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GlobalGroupLicenseFindUniqueArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GlobalGroupLicense that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GlobalGroupLicenseFindUniqueOrThrowArgs} args - Arguments to find a GlobalGroupLicense
   * @example
   * // Get one GlobalGroupLicense
   * const globalGroupLicense = await prisma.globalGroupLicense.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GlobalGroupLicenseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalGroupLicense that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseFindFirstArgs} args - Arguments to find a GlobalGroupLicense
   * @example
   * // Get one GlobalGroupLicense
   * const globalGroupLicense = await prisma.globalGroupLicense.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GlobalGroupLicenseFindFirstArgs>(args?: Prisma.SelectSubset<T, GlobalGroupLicenseFindFirstArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalGroupLicense that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseFindFirstOrThrowArgs} args - Arguments to find a GlobalGroupLicense
   * @example
   * // Get one GlobalGroupLicense
   * const globalGroupLicense = await prisma.globalGroupLicense.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GlobalGroupLicenseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GlobalGroupLicenseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GlobalGroupLicenses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GlobalGroupLicenses
   * const globalGroupLicenses = await prisma.globalGroupLicense.findMany()
   * 
   * // Get first 10 GlobalGroupLicenses
   * const globalGroupLicenses = await prisma.globalGroupLicense.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const globalGroupLicenseWithIdOnly = await prisma.globalGroupLicense.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GlobalGroupLicenseFindManyArgs>(args?: Prisma.SelectSubset<T, GlobalGroupLicenseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GlobalGroupLicense.
   * @param {GlobalGroupLicenseCreateArgs} args - Arguments to create a GlobalGroupLicense.
   * @example
   * // Create one GlobalGroupLicense
   * const GlobalGroupLicense = await prisma.globalGroupLicense.create({
   *   data: {
   *     // ... data to create a GlobalGroupLicense
   *   }
   * })
   * 
   */
  create<T extends GlobalGroupLicenseCreateArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseCreateArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GlobalGroupLicenses.
   * @param {GlobalGroupLicenseCreateManyArgs} args - Arguments to create many GlobalGroupLicenses.
   * @example
   * // Create many GlobalGroupLicenses
   * const globalGroupLicense = await prisma.globalGroupLicense.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GlobalGroupLicenseCreateManyArgs>(args?: Prisma.SelectSubset<T, GlobalGroupLicenseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a GlobalGroupLicense.
   * @param {GlobalGroupLicenseDeleteArgs} args - Arguments to delete one GlobalGroupLicense.
   * @example
   * // Delete one GlobalGroupLicense
   * const GlobalGroupLicense = await prisma.globalGroupLicense.delete({
   *   where: {
   *     // ... filter to delete one GlobalGroupLicense
   *   }
   * })
   * 
   */
  delete<T extends GlobalGroupLicenseDeleteArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseDeleteArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GlobalGroupLicense.
   * @param {GlobalGroupLicenseUpdateArgs} args - Arguments to update one GlobalGroupLicense.
   * @example
   * // Update one GlobalGroupLicense
   * const globalGroupLicense = await prisma.globalGroupLicense.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GlobalGroupLicenseUpdateArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseUpdateArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GlobalGroupLicenses.
   * @param {GlobalGroupLicenseDeleteManyArgs} args - Arguments to filter GlobalGroupLicenses to delete.
   * @example
   * // Delete a few GlobalGroupLicenses
   * const { count } = await prisma.globalGroupLicense.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GlobalGroupLicenseDeleteManyArgs>(args?: Prisma.SelectSubset<T, GlobalGroupLicenseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GlobalGroupLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GlobalGroupLicenses
   * const globalGroupLicense = await prisma.globalGroupLicense.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GlobalGroupLicenseUpdateManyArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one GlobalGroupLicense.
   * @param {GlobalGroupLicenseUpsertArgs} args - Arguments to update or create a GlobalGroupLicense.
   * @example
   * // Update or create a GlobalGroupLicense
   * const globalGroupLicense = await prisma.globalGroupLicense.upsert({
   *   create: {
   *     // ... data to create a GlobalGroupLicense
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GlobalGroupLicense we want to update
   *   }
   * })
   */
  upsert<T extends GlobalGroupLicenseUpsertArgs>(args: Prisma.SelectSubset<T, GlobalGroupLicenseUpsertArgs<ExtArgs>>): Prisma.Prisma__GlobalGroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GlobalGroupLicensePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GlobalGroupLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseCountArgs} args - Arguments to filter GlobalGroupLicenses to count.
   * @example
   * // Count the number of GlobalGroupLicenses
   * const count = await prisma.globalGroupLicense.count({
   *   where: {
   *     // ... the filter for the GlobalGroupLicenses we want to count
   *   }
   * })
  **/
  count<T extends GlobalGroupLicenseCountArgs>(
    args?: Prisma.Subset<T, GlobalGroupLicenseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GlobalGroupLicenseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GlobalGroupLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GlobalGroupLicenseAggregateArgs>(args: Prisma.Subset<T, GlobalGroupLicenseAggregateArgs>): Prisma.PrismaPromise<GetGlobalGroupLicenseAggregateType<T>>

  /**
   * Group by GlobalGroupLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalGroupLicenseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GlobalGroupLicenseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GlobalGroupLicenseGroupByArgs['orderBy'] }
      : { orderBy?: GlobalGroupLicenseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GlobalGroupLicenseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGlobalGroupLicenseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GlobalGroupLicense model
 */
readonly fields: GlobalGroupLicenseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GlobalGroupLicense.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GlobalGroupLicenseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GlobalGroupLicense model
 */
export interface GlobalGroupLicenseFieldRefs {
  readonly id: Prisma.FieldRef<"GlobalGroupLicense", 'String'>
  readonly robloxGroupId: Prisma.FieldRef<"GlobalGroupLicense", 'BigInt'>
  readonly accessType: Prisma.FieldRef<"GlobalGroupLicense", 'AccessType'>
  readonly reason: Prisma.FieldRef<"GlobalGroupLicense", 'String'>
  readonly createdAt: Prisma.FieldRef<"GlobalGroupLicense", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GlobalGroupLicense", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GlobalGroupLicense findUnique
 */
export type GlobalGroupLicenseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalGroupLicense to fetch.
   */
  where: Prisma.GlobalGroupLicenseWhereUniqueInput
}

/**
 * GlobalGroupLicense findUniqueOrThrow
 */
export type GlobalGroupLicenseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalGroupLicense to fetch.
   */
  where: Prisma.GlobalGroupLicenseWhereUniqueInput
}

/**
 * GlobalGroupLicense findFirst
 */
export type GlobalGroupLicenseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalGroupLicense to fetch.
   */
  where?: Prisma.GlobalGroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalGroupLicenses to fetch.
   */
  orderBy?: Prisma.GlobalGroupLicenseOrderByWithRelationInput | Prisma.GlobalGroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalGroupLicenses.
   */
  cursor?: Prisma.GlobalGroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalGroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalGroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalGroupLicenses.
   */
  distinct?: Prisma.GlobalGroupLicenseScalarFieldEnum | Prisma.GlobalGroupLicenseScalarFieldEnum[]
}

/**
 * GlobalGroupLicense findFirstOrThrow
 */
export type GlobalGroupLicenseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalGroupLicense to fetch.
   */
  where?: Prisma.GlobalGroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalGroupLicenses to fetch.
   */
  orderBy?: Prisma.GlobalGroupLicenseOrderByWithRelationInput | Prisma.GlobalGroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalGroupLicenses.
   */
  cursor?: Prisma.GlobalGroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalGroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalGroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalGroupLicenses.
   */
  distinct?: Prisma.GlobalGroupLicenseScalarFieldEnum | Prisma.GlobalGroupLicenseScalarFieldEnum[]
}

/**
 * GlobalGroupLicense findMany
 */
export type GlobalGroupLicenseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * Filter, which GlobalGroupLicenses to fetch.
   */
  where?: Prisma.GlobalGroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalGroupLicenses to fetch.
   */
  orderBy?: Prisma.GlobalGroupLicenseOrderByWithRelationInput | Prisma.GlobalGroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GlobalGroupLicenses.
   */
  cursor?: Prisma.GlobalGroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalGroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalGroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalGroupLicenses.
   */
  distinct?: Prisma.GlobalGroupLicenseScalarFieldEnum | Prisma.GlobalGroupLicenseScalarFieldEnum[]
}

/**
 * GlobalGroupLicense create
 */
export type GlobalGroupLicenseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * The data needed to create a GlobalGroupLicense.
   */
  data: Prisma.XOR<Prisma.GlobalGroupLicenseCreateInput, Prisma.GlobalGroupLicenseUncheckedCreateInput>
}

/**
 * GlobalGroupLicense createMany
 */
export type GlobalGroupLicenseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GlobalGroupLicenses.
   */
  data: Prisma.GlobalGroupLicenseCreateManyInput | Prisma.GlobalGroupLicenseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GlobalGroupLicense update
 */
export type GlobalGroupLicenseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * The data needed to update a GlobalGroupLicense.
   */
  data: Prisma.XOR<Prisma.GlobalGroupLicenseUpdateInput, Prisma.GlobalGroupLicenseUncheckedUpdateInput>
  /**
   * Choose, which GlobalGroupLicense to update.
   */
  where: Prisma.GlobalGroupLicenseWhereUniqueInput
}

/**
 * GlobalGroupLicense updateMany
 */
export type GlobalGroupLicenseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GlobalGroupLicenses.
   */
  data: Prisma.XOR<Prisma.GlobalGroupLicenseUpdateManyMutationInput, Prisma.GlobalGroupLicenseUncheckedUpdateManyInput>
  /**
   * Filter which GlobalGroupLicenses to update
   */
  where?: Prisma.GlobalGroupLicenseWhereInput
  /**
   * Limit how many GlobalGroupLicenses to update.
   */
  limit?: number
}

/**
 * GlobalGroupLicense upsert
 */
export type GlobalGroupLicenseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * The filter to search for the GlobalGroupLicense to update in case it exists.
   */
  where: Prisma.GlobalGroupLicenseWhereUniqueInput
  /**
   * In case the GlobalGroupLicense found by the `where` argument doesn't exist, create a new GlobalGroupLicense with this data.
   */
  create: Prisma.XOR<Prisma.GlobalGroupLicenseCreateInput, Prisma.GlobalGroupLicenseUncheckedCreateInput>
  /**
   * In case the GlobalGroupLicense was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GlobalGroupLicenseUpdateInput, Prisma.GlobalGroupLicenseUncheckedUpdateInput>
}

/**
 * GlobalGroupLicense delete
 */
export type GlobalGroupLicenseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
  /**
   * Filter which GlobalGroupLicense to delete.
   */
  where: Prisma.GlobalGroupLicenseWhereUniqueInput
}

/**
 * GlobalGroupLicense deleteMany
 */
export type GlobalGroupLicenseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalGroupLicenses to delete
   */
  where?: Prisma.GlobalGroupLicenseWhereInput
  /**
   * Limit how many GlobalGroupLicenses to delete.
   */
  limit?: number
}

/**
 * GlobalGroupLicense without action
 */
export type GlobalGroupLicenseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalGroupLicense
   */
  select?: Prisma.GlobalGroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalGroupLicense
   */
  omit?: Prisma.GlobalGroupLicenseOmit<ExtArgs> | null
}
