
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GroupLicense` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GroupLicense
 * 
 */
export type GroupLicenseModel = runtime.Types.Result.DefaultSelection<Prisma.$GroupLicensePayload>

export type AggregateGroupLicense = {
  _count: GroupLicenseCountAggregateOutputType | null
  _avg: GroupLicenseAvgAggregateOutputType | null
  _sum: GroupLicenseSumAggregateOutputType | null
  _min: GroupLicenseMinAggregateOutputType | null
  _max: GroupLicenseMaxAggregateOutputType | null
}

export type GroupLicenseAvgAggregateOutputType = {
  robloxGroupId: number | null
}

export type GroupLicenseSumAggregateOutputType = {
  robloxGroupId: bigint | null
}

export type GroupLicenseMinAggregateOutputType = {
  id: string | null
  robloxGroupId: bigint | null
  productId: string | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GroupLicenseMaxAggregateOutputType = {
  id: string | null
  robloxGroupId: bigint | null
  productId: string | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GroupLicenseCountAggregateOutputType = {
  id: number
  robloxGroupId: number
  productId: number
  accessType: number
  reason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GroupLicenseAvgAggregateInputType = {
  robloxGroupId?: true
}

export type GroupLicenseSumAggregateInputType = {
  robloxGroupId?: true
}

export type GroupLicenseMinAggregateInputType = {
  id?: true
  robloxGroupId?: true
  productId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type GroupLicenseMaxAggregateInputType = {
  id?: true
  robloxGroupId?: true
  productId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type GroupLicenseCountAggregateInputType = {
  id?: true
  robloxGroupId?: true
  productId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GroupLicenseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GroupLicense to aggregate.
   */
  where?: Prisma.GroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GroupLicenses to fetch.
   */
  orderBy?: Prisma.GroupLicenseOrderByWithRelationInput | Prisma.GroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GroupLicenses
  **/
  _count?: true | GroupLicenseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GroupLicenseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GroupLicenseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GroupLicenseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GroupLicenseMaxAggregateInputType
}

export type GetGroupLicenseAggregateType<T extends GroupLicenseAggregateArgs> = {
      [P in keyof T & keyof AggregateGroupLicense]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGroupLicense[P]>
    : Prisma.GetScalarType<T[P], AggregateGroupLicense[P]>
}




export type GroupLicenseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GroupLicenseWhereInput
  orderBy?: Prisma.GroupLicenseOrderByWithAggregationInput | Prisma.GroupLicenseOrderByWithAggregationInput[]
  by: Prisma.GroupLicenseScalarFieldEnum[] | Prisma.GroupLicenseScalarFieldEnum
  having?: Prisma.GroupLicenseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GroupLicenseCountAggregateInputType | true
  _avg?: GroupLicenseAvgAggregateInputType
  _sum?: GroupLicenseSumAggregateInputType
  _min?: GroupLicenseMinAggregateInputType
  _max?: GroupLicenseMaxAggregateInputType
}

export type GroupLicenseGroupByOutputType = {
  id: string
  robloxGroupId: bigint
  productId: string
  accessType: $Enums.AccessType
  reason: string | null
  createdAt: Date
  updatedAt: Date
  _count: GroupLicenseCountAggregateOutputType | null
  _avg: GroupLicenseAvgAggregateOutputType | null
  _sum: GroupLicenseSumAggregateOutputType | null
  _min: GroupLicenseMinAggregateOutputType | null
  _max: GroupLicenseMaxAggregateOutputType | null
}

export type GetGroupLicenseGroupByPayload<T extends GroupLicenseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GroupLicenseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GroupLicenseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GroupLicenseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GroupLicenseGroupByOutputType[P]>
      }
    >
  >



export type GroupLicenseWhereInput = {
  AND?: Prisma.GroupLicenseWhereInput | Prisma.GroupLicenseWhereInput[]
  OR?: Prisma.GroupLicenseWhereInput[]
  NOT?: Prisma.GroupLicenseWhereInput | Prisma.GroupLicenseWhereInput[]
  id?: Prisma.StringFilter<"GroupLicense"> | string
  robloxGroupId?: Prisma.BigIntFilter<"GroupLicense"> | bigint | number
  productId?: Prisma.StringFilter<"GroupLicense"> | string
  accessType?: Prisma.EnumAccessTypeFilter<"GroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GroupLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GroupLicense"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type GroupLicenseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  _relevance?: Prisma.GroupLicenseOrderByRelevanceInput
}

export type GroupLicenseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  robloxGroupId_productId?: Prisma.GroupLicenseRobloxGroupIdProductIdCompoundUniqueInput
  AND?: Prisma.GroupLicenseWhereInput | Prisma.GroupLicenseWhereInput[]
  OR?: Prisma.GroupLicenseWhereInput[]
  NOT?: Prisma.GroupLicenseWhereInput | Prisma.GroupLicenseWhereInput[]
  robloxGroupId?: Prisma.BigIntFilter<"GroupLicense"> | bigint | number
  productId?: Prisma.StringFilter<"GroupLicense"> | string
  accessType?: Prisma.EnumAccessTypeFilter<"GroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GroupLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GroupLicense"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "robloxGroupId_productId">

export type GroupLicenseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GroupLicenseCountOrderByAggregateInput
  _avg?: Prisma.GroupLicenseAvgOrderByAggregateInput
  _max?: Prisma.GroupLicenseMaxOrderByAggregateInput
  _min?: Prisma.GroupLicenseMinOrderByAggregateInput
  _sum?: Prisma.GroupLicenseSumOrderByAggregateInput
}

export type GroupLicenseScalarWhereWithAggregatesInput = {
  AND?: Prisma.GroupLicenseScalarWhereWithAggregatesInput | Prisma.GroupLicenseScalarWhereWithAggregatesInput[]
  OR?: Prisma.GroupLicenseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GroupLicenseScalarWhereWithAggregatesInput | Prisma.GroupLicenseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GroupLicense"> | string
  robloxGroupId?: Prisma.BigIntWithAggregatesFilter<"GroupLicense"> | bigint | number
  productId?: Prisma.StringWithAggregatesFilter<"GroupLicense"> | string
  accessType?: Prisma.EnumAccessTypeWithAggregatesFilter<"GroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableWithAggregatesFilter<"GroupLicense"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GroupLicense"> | Date | string
}

export type GroupLicenseCreateInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutGroupLicensesInput
}

export type GroupLicenseUncheckedCreateInput = {
  id?: string
  robloxGroupId: bigint | number
  productId: string
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GroupLicenseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutGroupLicensesNestedInput
}

export type GroupLicenseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GroupLicenseCreateManyInput = {
  id?: string
  robloxGroupId: bigint | number
  productId: string
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GroupLicenseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GroupLicenseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GroupLicenseListRelationFilter = {
  every?: Prisma.GroupLicenseWhereInput
  some?: Prisma.GroupLicenseWhereInput
  none?: Prisma.GroupLicenseWhereInput
}

export type GroupLicenseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GroupLicenseOrderByRelevanceInput = {
  fields: Prisma.GroupLicenseOrderByRelevanceFieldEnum | Prisma.GroupLicenseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type GroupLicenseRobloxGroupIdProductIdCompoundUniqueInput = {
  robloxGroupId: bigint | number
  productId: string
}

export type GroupLicenseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GroupLicenseAvgOrderByAggregateInput = {
  robloxGroupId?: Prisma.SortOrder
}

export type GroupLicenseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GroupLicenseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxGroupId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GroupLicenseSumOrderByAggregateInput = {
  robloxGroupId?: Prisma.SortOrder
}

export type GroupLicenseCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.GroupLicenseCreateWithoutProductInput, Prisma.GroupLicenseUncheckedCreateWithoutProductInput> | Prisma.GroupLicenseCreateWithoutProductInput[] | Prisma.GroupLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.GroupLicenseCreateOrConnectWithoutProductInput | Prisma.GroupLicenseCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.GroupLicenseCreateManyProductInputEnvelope
  connect?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
}

export type GroupLicenseUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.GroupLicenseCreateWithoutProductInput, Prisma.GroupLicenseUncheckedCreateWithoutProductInput> | Prisma.GroupLicenseCreateWithoutProductInput[] | Prisma.GroupLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.GroupLicenseCreateOrConnectWithoutProductInput | Prisma.GroupLicenseCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.GroupLicenseCreateManyProductInputEnvelope
  connect?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
}

export type GroupLicenseUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.GroupLicenseCreateWithoutProductInput, Prisma.GroupLicenseUncheckedCreateWithoutProductInput> | Prisma.GroupLicenseCreateWithoutProductInput[] | Prisma.GroupLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.GroupLicenseCreateOrConnectWithoutProductInput | Prisma.GroupLicenseCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.GroupLicenseUpsertWithWhereUniqueWithoutProductInput | Prisma.GroupLicenseUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.GroupLicenseCreateManyProductInputEnvelope
  set?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  disconnect?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  delete?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  connect?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  update?: Prisma.GroupLicenseUpdateWithWhereUniqueWithoutProductInput | Prisma.GroupLicenseUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.GroupLicenseUpdateManyWithWhereWithoutProductInput | Prisma.GroupLicenseUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.GroupLicenseScalarWhereInput | Prisma.GroupLicenseScalarWhereInput[]
}

export type GroupLicenseUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.GroupLicenseCreateWithoutProductInput, Prisma.GroupLicenseUncheckedCreateWithoutProductInput> | Prisma.GroupLicenseCreateWithoutProductInput[] | Prisma.GroupLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.GroupLicenseCreateOrConnectWithoutProductInput | Prisma.GroupLicenseCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.GroupLicenseUpsertWithWhereUniqueWithoutProductInput | Prisma.GroupLicenseUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.GroupLicenseCreateManyProductInputEnvelope
  set?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  disconnect?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  delete?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  connect?: Prisma.GroupLicenseWhereUniqueInput | Prisma.GroupLicenseWhereUniqueInput[]
  update?: Prisma.GroupLicenseUpdateWithWhereUniqueWithoutProductInput | Prisma.GroupLicenseUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.GroupLicenseUpdateManyWithWhereWithoutProductInput | Prisma.GroupLicenseUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.GroupLicenseScalarWhereInput | Prisma.GroupLicenseScalarWhereInput[]
}

export type GroupLicenseCreateWithoutProductInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GroupLicenseUncheckedCreateWithoutProductInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GroupLicenseCreateOrConnectWithoutProductInput = {
  where: Prisma.GroupLicenseWhereUniqueInput
  create: Prisma.XOR<Prisma.GroupLicenseCreateWithoutProductInput, Prisma.GroupLicenseUncheckedCreateWithoutProductInput>
}

export type GroupLicenseCreateManyProductInputEnvelope = {
  data: Prisma.GroupLicenseCreateManyProductInput | Prisma.GroupLicenseCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type GroupLicenseUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.GroupLicenseWhereUniqueInput
  update: Prisma.XOR<Prisma.GroupLicenseUpdateWithoutProductInput, Prisma.GroupLicenseUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.GroupLicenseCreateWithoutProductInput, Prisma.GroupLicenseUncheckedCreateWithoutProductInput>
}

export type GroupLicenseUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.GroupLicenseWhereUniqueInput
  data: Prisma.XOR<Prisma.GroupLicenseUpdateWithoutProductInput, Prisma.GroupLicenseUncheckedUpdateWithoutProductInput>
}

export type GroupLicenseUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.GroupLicenseScalarWhereInput
  data: Prisma.XOR<Prisma.GroupLicenseUpdateManyMutationInput, Prisma.GroupLicenseUncheckedUpdateManyWithoutProductInput>
}

export type GroupLicenseScalarWhereInput = {
  AND?: Prisma.GroupLicenseScalarWhereInput | Prisma.GroupLicenseScalarWhereInput[]
  OR?: Prisma.GroupLicenseScalarWhereInput[]
  NOT?: Prisma.GroupLicenseScalarWhereInput | Prisma.GroupLicenseScalarWhereInput[]
  id?: Prisma.StringFilter<"GroupLicense"> | string
  robloxGroupId?: Prisma.BigIntFilter<"GroupLicense"> | bigint | number
  productId?: Prisma.StringFilter<"GroupLicense"> | string
  accessType?: Prisma.EnumAccessTypeFilter<"GroupLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"GroupLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GroupLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GroupLicense"> | Date | string
}

export type GroupLicenseCreateManyProductInput = {
  id?: string
  robloxGroupId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GroupLicenseUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GroupLicenseUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GroupLicenseUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxGroupId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GroupLicenseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  robloxGroupId?: boolean
  productId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["groupLicense"]>



export type GroupLicenseSelectScalar = {
  id?: boolean
  robloxGroupId?: boolean
  productId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GroupLicenseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "robloxGroupId" | "productId" | "accessType" | "reason" | "createdAt" | "updatedAt", ExtArgs["result"]["groupLicense"]>
export type GroupLicenseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $GroupLicensePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GroupLicense"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    robloxGroupId: bigint
    productId: string
    accessType: $Enums.AccessType
    reason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["groupLicense"]>
  composites: {}
}

export type GroupLicenseGetPayload<S extends boolean | null | undefined | GroupLicenseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload, S>

export type GroupLicenseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GroupLicenseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GroupLicenseCountAggregateInputType | true
  }

export interface GroupLicenseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GroupLicense'], meta: { name: 'GroupLicense' } }
  /**
   * Find zero or one GroupLicense that matches the filter.
   * @param {GroupLicenseFindUniqueArgs} args - Arguments to find a GroupLicense
   * @example
   * // Get one GroupLicense
   * const groupLicense = await prisma.groupLicense.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GroupLicenseFindUniqueArgs>(args: Prisma.SelectSubset<T, GroupLicenseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GroupLicense that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GroupLicenseFindUniqueOrThrowArgs} args - Arguments to find a GroupLicense
   * @example
   * // Get one GroupLicense
   * const groupLicense = await prisma.groupLicense.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GroupLicenseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GroupLicenseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GroupLicense that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseFindFirstArgs} args - Arguments to find a GroupLicense
   * @example
   * // Get one GroupLicense
   * const groupLicense = await prisma.groupLicense.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GroupLicenseFindFirstArgs>(args?: Prisma.SelectSubset<T, GroupLicenseFindFirstArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GroupLicense that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseFindFirstOrThrowArgs} args - Arguments to find a GroupLicense
   * @example
   * // Get one GroupLicense
   * const groupLicense = await prisma.groupLicense.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GroupLicenseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GroupLicenseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GroupLicenses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GroupLicenses
   * const groupLicenses = await prisma.groupLicense.findMany()
   * 
   * // Get first 10 GroupLicenses
   * const groupLicenses = await prisma.groupLicense.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const groupLicenseWithIdOnly = await prisma.groupLicense.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GroupLicenseFindManyArgs>(args?: Prisma.SelectSubset<T, GroupLicenseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GroupLicense.
   * @param {GroupLicenseCreateArgs} args - Arguments to create a GroupLicense.
   * @example
   * // Create one GroupLicense
   * const GroupLicense = await prisma.groupLicense.create({
   *   data: {
   *     // ... data to create a GroupLicense
   *   }
   * })
   * 
   */
  create<T extends GroupLicenseCreateArgs>(args: Prisma.SelectSubset<T, GroupLicenseCreateArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GroupLicenses.
   * @param {GroupLicenseCreateManyArgs} args - Arguments to create many GroupLicenses.
   * @example
   * // Create many GroupLicenses
   * const groupLicense = await prisma.groupLicense.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GroupLicenseCreateManyArgs>(args?: Prisma.SelectSubset<T, GroupLicenseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a GroupLicense.
   * @param {GroupLicenseDeleteArgs} args - Arguments to delete one GroupLicense.
   * @example
   * // Delete one GroupLicense
   * const GroupLicense = await prisma.groupLicense.delete({
   *   where: {
   *     // ... filter to delete one GroupLicense
   *   }
   * })
   * 
   */
  delete<T extends GroupLicenseDeleteArgs>(args: Prisma.SelectSubset<T, GroupLicenseDeleteArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GroupLicense.
   * @param {GroupLicenseUpdateArgs} args - Arguments to update one GroupLicense.
   * @example
   * // Update one GroupLicense
   * const groupLicense = await prisma.groupLicense.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GroupLicenseUpdateArgs>(args: Prisma.SelectSubset<T, GroupLicenseUpdateArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GroupLicenses.
   * @param {GroupLicenseDeleteManyArgs} args - Arguments to filter GroupLicenses to delete.
   * @example
   * // Delete a few GroupLicenses
   * const { count } = await prisma.groupLicense.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GroupLicenseDeleteManyArgs>(args?: Prisma.SelectSubset<T, GroupLicenseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GroupLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GroupLicenses
   * const groupLicense = await prisma.groupLicense.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GroupLicenseUpdateManyArgs>(args: Prisma.SelectSubset<T, GroupLicenseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one GroupLicense.
   * @param {GroupLicenseUpsertArgs} args - Arguments to update or create a GroupLicense.
   * @example
   * // Update or create a GroupLicense
   * const groupLicense = await prisma.groupLicense.upsert({
   *   create: {
   *     // ... data to create a GroupLicense
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GroupLicense we want to update
   *   }
   * })
   */
  upsert<T extends GroupLicenseUpsertArgs>(args: Prisma.SelectSubset<T, GroupLicenseUpsertArgs<ExtArgs>>): Prisma.Prisma__GroupLicenseClient<runtime.Types.Result.GetResult<Prisma.$GroupLicensePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GroupLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseCountArgs} args - Arguments to filter GroupLicenses to count.
   * @example
   * // Count the number of GroupLicenses
   * const count = await prisma.groupLicense.count({
   *   where: {
   *     // ... the filter for the GroupLicenses we want to count
   *   }
   * })
  **/
  count<T extends GroupLicenseCountArgs>(
    args?: Prisma.Subset<T, GroupLicenseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GroupLicenseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GroupLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GroupLicenseAggregateArgs>(args: Prisma.Subset<T, GroupLicenseAggregateArgs>): Prisma.PrismaPromise<GetGroupLicenseAggregateType<T>>

  /**
   * Group by GroupLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GroupLicenseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GroupLicenseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GroupLicenseGroupByArgs['orderBy'] }
      : { orderBy?: GroupLicenseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GroupLicenseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGroupLicenseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GroupLicense model
 */
readonly fields: GroupLicenseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GroupLicense.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GroupLicenseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GroupLicense model
 */
export interface GroupLicenseFieldRefs {
  readonly id: Prisma.FieldRef<"GroupLicense", 'String'>
  readonly robloxGroupId: Prisma.FieldRef<"GroupLicense", 'BigInt'>
  readonly productId: Prisma.FieldRef<"GroupLicense", 'String'>
  readonly accessType: Prisma.FieldRef<"GroupLicense", 'AccessType'>
  readonly reason: Prisma.FieldRef<"GroupLicense", 'String'>
  readonly createdAt: Prisma.FieldRef<"GroupLicense", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GroupLicense", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GroupLicense findUnique
 */
export type GroupLicenseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * Filter, which GroupLicense to fetch.
   */
  where: Prisma.GroupLicenseWhereUniqueInput
}

/**
 * GroupLicense findUniqueOrThrow
 */
export type GroupLicenseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * Filter, which GroupLicense to fetch.
   */
  where: Prisma.GroupLicenseWhereUniqueInput
}

/**
 * GroupLicense findFirst
 */
export type GroupLicenseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * Filter, which GroupLicense to fetch.
   */
  where?: Prisma.GroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GroupLicenses to fetch.
   */
  orderBy?: Prisma.GroupLicenseOrderByWithRelationInput | Prisma.GroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GroupLicenses.
   */
  cursor?: Prisma.GroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GroupLicenses.
   */
  distinct?: Prisma.GroupLicenseScalarFieldEnum | Prisma.GroupLicenseScalarFieldEnum[]
}

/**
 * GroupLicense findFirstOrThrow
 */
export type GroupLicenseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * Filter, which GroupLicense to fetch.
   */
  where?: Prisma.GroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GroupLicenses to fetch.
   */
  orderBy?: Prisma.GroupLicenseOrderByWithRelationInput | Prisma.GroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GroupLicenses.
   */
  cursor?: Prisma.GroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GroupLicenses.
   */
  distinct?: Prisma.GroupLicenseScalarFieldEnum | Prisma.GroupLicenseScalarFieldEnum[]
}

/**
 * GroupLicense findMany
 */
export type GroupLicenseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * Filter, which GroupLicenses to fetch.
   */
  where?: Prisma.GroupLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GroupLicenses to fetch.
   */
  orderBy?: Prisma.GroupLicenseOrderByWithRelationInput | Prisma.GroupLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GroupLicenses.
   */
  cursor?: Prisma.GroupLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GroupLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GroupLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GroupLicenses.
   */
  distinct?: Prisma.GroupLicenseScalarFieldEnum | Prisma.GroupLicenseScalarFieldEnum[]
}

/**
 * GroupLicense create
 */
export type GroupLicenseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * The data needed to create a GroupLicense.
   */
  data: Prisma.XOR<Prisma.GroupLicenseCreateInput, Prisma.GroupLicenseUncheckedCreateInput>
}

/**
 * GroupLicense createMany
 */
export type GroupLicenseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GroupLicenses.
   */
  data: Prisma.GroupLicenseCreateManyInput | Prisma.GroupLicenseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GroupLicense update
 */
export type GroupLicenseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * The data needed to update a GroupLicense.
   */
  data: Prisma.XOR<Prisma.GroupLicenseUpdateInput, Prisma.GroupLicenseUncheckedUpdateInput>
  /**
   * Choose, which GroupLicense to update.
   */
  where: Prisma.GroupLicenseWhereUniqueInput
}

/**
 * GroupLicense updateMany
 */
export type GroupLicenseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GroupLicenses.
   */
  data: Prisma.XOR<Prisma.GroupLicenseUpdateManyMutationInput, Prisma.GroupLicenseUncheckedUpdateManyInput>
  /**
   * Filter which GroupLicenses to update
   */
  where?: Prisma.GroupLicenseWhereInput
  /**
   * Limit how many GroupLicenses to update.
   */
  limit?: number
}

/**
 * GroupLicense upsert
 */
export type GroupLicenseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * The filter to search for the GroupLicense to update in case it exists.
   */
  where: Prisma.GroupLicenseWhereUniqueInput
  /**
   * In case the GroupLicense found by the `where` argument doesn't exist, create a new GroupLicense with this data.
   */
  create: Prisma.XOR<Prisma.GroupLicenseCreateInput, Prisma.GroupLicenseUncheckedCreateInput>
  /**
   * In case the GroupLicense was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GroupLicenseUpdateInput, Prisma.GroupLicenseUncheckedUpdateInput>
}

/**
 * GroupLicense delete
 */
export type GroupLicenseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
  /**
   * Filter which GroupLicense to delete.
   */
  where: Prisma.GroupLicenseWhereUniqueInput
}

/**
 * GroupLicense deleteMany
 */
export type GroupLicenseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GroupLicenses to delete
   */
  where?: Prisma.GroupLicenseWhereInput
  /**
   * Limit how many GroupLicenses to delete.
   */
  limit?: number
}

/**
 * GroupLicense without action
 */
export type GroupLicenseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupLicense
   */
  select?: Prisma.GroupLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupLicense
   */
  omit?: Prisma.GroupLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupLicenseInclude<ExtArgs> | null
}
