
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserLicense` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserLicense
 * 
 */
export type UserLicenseModel = runtime.Types.Result.DefaultSelection<Prisma.$UserLicensePayload>

export type AggregateUserLicense = {
  _count: UserLicenseCountAggregateOutputType | null
  _avg: UserLicenseAvgAggregateOutputType | null
  _sum: UserLicenseSumAggregateOutputType | null
  _min: UserLicenseMinAggregateOutputType | null
  _max: UserLicenseMaxAggregateOutputType | null
}

export type UserLicenseAvgAggregateOutputType = {
  robloxUserId: number | null
}

export type UserLicenseSumAggregateOutputType = {
  robloxUserId: bigint | null
}

export type UserLicenseMinAggregateOutputType = {
  id: string | null
  robloxUserId: bigint | null
  productId: string | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserLicenseMaxAggregateOutputType = {
  id: string | null
  robloxUserId: bigint | null
  productId: string | null
  accessType: $Enums.AccessType | null
  reason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserLicenseCountAggregateOutputType = {
  id: number
  robloxUserId: number
  productId: number
  accessType: number
  reason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserLicenseAvgAggregateInputType = {
  robloxUserId?: true
}

export type UserLicenseSumAggregateInputType = {
  robloxUserId?: true
}

export type UserLicenseMinAggregateInputType = {
  id?: true
  robloxUserId?: true
  productId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type UserLicenseMaxAggregateInputType = {
  id?: true
  robloxUserId?: true
  productId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
}

export type UserLicenseCountAggregateInputType = {
  id?: true
  robloxUserId?: true
  productId?: true
  accessType?: true
  reason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserLicenseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserLicense to aggregate.
   */
  where?: Prisma.UserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserLicenses to fetch.
   */
  orderBy?: Prisma.UserLicenseOrderByWithRelationInput | Prisma.UserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserLicenses
  **/
  _count?: true | UserLicenseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserLicenseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserLicenseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserLicenseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserLicenseMaxAggregateInputType
}

export type GetUserLicenseAggregateType<T extends UserLicenseAggregateArgs> = {
      [P in keyof T & keyof AggregateUserLicense]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserLicense[P]>
    : Prisma.GetScalarType<T[P], AggregateUserLicense[P]>
}




export type UserLicenseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserLicenseWhereInput
  orderBy?: Prisma.UserLicenseOrderByWithAggregationInput | Prisma.UserLicenseOrderByWithAggregationInput[]
  by: Prisma.UserLicenseScalarFieldEnum[] | Prisma.UserLicenseScalarFieldEnum
  having?: Prisma.UserLicenseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserLicenseCountAggregateInputType | true
  _avg?: UserLicenseAvgAggregateInputType
  _sum?: UserLicenseSumAggregateInputType
  _min?: UserLicenseMinAggregateInputType
  _max?: UserLicenseMaxAggregateInputType
}

export type UserLicenseGroupByOutputType = {
  id: string
  robloxUserId: bigint
  productId: string
  accessType: $Enums.AccessType
  reason: string | null
  createdAt: Date
  updatedAt: Date
  _count: UserLicenseCountAggregateOutputType | null
  _avg: UserLicenseAvgAggregateOutputType | null
  _sum: UserLicenseSumAggregateOutputType | null
  _min: UserLicenseMinAggregateOutputType | null
  _max: UserLicenseMaxAggregateOutputType | null
}

export type GetUserLicenseGroupByPayload<T extends UserLicenseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserLicenseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserLicenseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserLicenseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserLicenseGroupByOutputType[P]>
      }
    >
  >



export type UserLicenseWhereInput = {
  AND?: Prisma.UserLicenseWhereInput | Prisma.UserLicenseWhereInput[]
  OR?: Prisma.UserLicenseWhereInput[]
  NOT?: Prisma.UserLicenseWhereInput | Prisma.UserLicenseWhereInput[]
  id?: Prisma.StringFilter<"UserLicense"> | string
  robloxUserId?: Prisma.BigIntFilter<"UserLicense"> | bigint | number
  productId?: Prisma.StringFilter<"UserLicense"> | string
  accessType?: Prisma.EnumAccessTypeFilter<"UserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"UserLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserLicense"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type UserLicenseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  _relevance?: Prisma.UserLicenseOrderByRelevanceInput
}

export type UserLicenseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  robloxUserId_productId?: Prisma.UserLicenseRobloxUserIdProductIdCompoundUniqueInput
  AND?: Prisma.UserLicenseWhereInput | Prisma.UserLicenseWhereInput[]
  OR?: Prisma.UserLicenseWhereInput[]
  NOT?: Prisma.UserLicenseWhereInput | Prisma.UserLicenseWhereInput[]
  robloxUserId?: Prisma.BigIntFilter<"UserLicense"> | bigint | number
  productId?: Prisma.StringFilter<"UserLicense"> | string
  accessType?: Prisma.EnumAccessTypeFilter<"UserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"UserLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserLicense"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "robloxUserId_productId">

export type UserLicenseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserLicenseCountOrderByAggregateInput
  _avg?: Prisma.UserLicenseAvgOrderByAggregateInput
  _max?: Prisma.UserLicenseMaxOrderByAggregateInput
  _min?: Prisma.UserLicenseMinOrderByAggregateInput
  _sum?: Prisma.UserLicenseSumOrderByAggregateInput
}

export type UserLicenseScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserLicenseScalarWhereWithAggregatesInput | Prisma.UserLicenseScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserLicenseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserLicenseScalarWhereWithAggregatesInput | Prisma.UserLicenseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserLicense"> | string
  robloxUserId?: Prisma.BigIntWithAggregatesFilter<"UserLicense"> | bigint | number
  productId?: Prisma.StringWithAggregatesFilter<"UserLicense"> | string
  accessType?: Prisma.EnumAccessTypeWithAggregatesFilter<"UserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableWithAggregatesFilter<"UserLicense"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserLicense"> | Date | string
}

export type UserLicenseCreateInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutUserLicensesInput
}

export type UserLicenseUncheckedCreateInput = {
  id?: string
  robloxUserId: bigint | number
  productId: string
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserLicenseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutUserLicensesNestedInput
}

export type UserLicenseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserLicenseCreateManyInput = {
  id?: string
  robloxUserId: bigint | number
  productId: string
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserLicenseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserLicenseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserLicenseListRelationFilter = {
  every?: Prisma.UserLicenseWhereInput
  some?: Prisma.UserLicenseWhereInput
  none?: Prisma.UserLicenseWhereInput
}

export type UserLicenseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserLicenseOrderByRelevanceInput = {
  fields: Prisma.UserLicenseOrderByRelevanceFieldEnum | Prisma.UserLicenseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserLicenseRobloxUserIdProductIdCompoundUniqueInput = {
  robloxUserId: bigint | number
  productId: string
}

export type UserLicenseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserLicenseAvgOrderByAggregateInput = {
  robloxUserId?: Prisma.SortOrder
}

export type UserLicenseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserLicenseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  robloxUserId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  accessType?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserLicenseSumOrderByAggregateInput = {
  robloxUserId?: Prisma.SortOrder
}

export type UserLicenseCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.UserLicenseCreateWithoutProductInput, Prisma.UserLicenseUncheckedCreateWithoutProductInput> | Prisma.UserLicenseCreateWithoutProductInput[] | Prisma.UserLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.UserLicenseCreateOrConnectWithoutProductInput | Prisma.UserLicenseCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.UserLicenseCreateManyProductInputEnvelope
  connect?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
}

export type UserLicenseUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.UserLicenseCreateWithoutProductInput, Prisma.UserLicenseUncheckedCreateWithoutProductInput> | Prisma.UserLicenseCreateWithoutProductInput[] | Prisma.UserLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.UserLicenseCreateOrConnectWithoutProductInput | Prisma.UserLicenseCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.UserLicenseCreateManyProductInputEnvelope
  connect?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
}

export type UserLicenseUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.UserLicenseCreateWithoutProductInput, Prisma.UserLicenseUncheckedCreateWithoutProductInput> | Prisma.UserLicenseCreateWithoutProductInput[] | Prisma.UserLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.UserLicenseCreateOrConnectWithoutProductInput | Prisma.UserLicenseCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.UserLicenseUpsertWithWhereUniqueWithoutProductInput | Prisma.UserLicenseUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.UserLicenseCreateManyProductInputEnvelope
  set?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  disconnect?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  delete?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  connect?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  update?: Prisma.UserLicenseUpdateWithWhereUniqueWithoutProductInput | Prisma.UserLicenseUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.UserLicenseUpdateManyWithWhereWithoutProductInput | Prisma.UserLicenseUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.UserLicenseScalarWhereInput | Prisma.UserLicenseScalarWhereInput[]
}

export type UserLicenseUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.UserLicenseCreateWithoutProductInput, Prisma.UserLicenseUncheckedCreateWithoutProductInput> | Prisma.UserLicenseCreateWithoutProductInput[] | Prisma.UserLicenseUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.UserLicenseCreateOrConnectWithoutProductInput | Prisma.UserLicenseCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.UserLicenseUpsertWithWhereUniqueWithoutProductInput | Prisma.UserLicenseUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.UserLicenseCreateManyProductInputEnvelope
  set?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  disconnect?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  delete?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  connect?: Prisma.UserLicenseWhereUniqueInput | Prisma.UserLicenseWhereUniqueInput[]
  update?: Prisma.UserLicenseUpdateWithWhereUniqueWithoutProductInput | Prisma.UserLicenseUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.UserLicenseUpdateManyWithWhereWithoutProductInput | Prisma.UserLicenseUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.UserLicenseScalarWhereInput | Prisma.UserLicenseScalarWhereInput[]
}

export type UserLicenseCreateWithoutProductInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserLicenseUncheckedCreateWithoutProductInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserLicenseCreateOrConnectWithoutProductInput = {
  where: Prisma.UserLicenseWhereUniqueInput
  create: Prisma.XOR<Prisma.UserLicenseCreateWithoutProductInput, Prisma.UserLicenseUncheckedCreateWithoutProductInput>
}

export type UserLicenseCreateManyProductInputEnvelope = {
  data: Prisma.UserLicenseCreateManyProductInput | Prisma.UserLicenseCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type UserLicenseUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.UserLicenseWhereUniqueInput
  update: Prisma.XOR<Prisma.UserLicenseUpdateWithoutProductInput, Prisma.UserLicenseUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.UserLicenseCreateWithoutProductInput, Prisma.UserLicenseUncheckedCreateWithoutProductInput>
}

export type UserLicenseUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.UserLicenseWhereUniqueInput
  data: Prisma.XOR<Prisma.UserLicenseUpdateWithoutProductInput, Prisma.UserLicenseUncheckedUpdateWithoutProductInput>
}

export type UserLicenseUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.UserLicenseScalarWhereInput
  data: Prisma.XOR<Prisma.UserLicenseUpdateManyMutationInput, Prisma.UserLicenseUncheckedUpdateManyWithoutProductInput>
}

export type UserLicenseScalarWhereInput = {
  AND?: Prisma.UserLicenseScalarWhereInput | Prisma.UserLicenseScalarWhereInput[]
  OR?: Prisma.UserLicenseScalarWhereInput[]
  NOT?: Prisma.UserLicenseScalarWhereInput | Prisma.UserLicenseScalarWhereInput[]
  id?: Prisma.StringFilter<"UserLicense"> | string
  robloxUserId?: Prisma.BigIntFilter<"UserLicense"> | bigint | number
  productId?: Prisma.StringFilter<"UserLicense"> | string
  accessType?: Prisma.EnumAccessTypeFilter<"UserLicense"> | $Enums.AccessType
  reason?: Prisma.StringNullableFilter<"UserLicense"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserLicense"> | Date | string
}

export type UserLicenseCreateManyProductInput = {
  id?: string
  robloxUserId: bigint | number
  accessType?: $Enums.AccessType
  reason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserLicenseUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserLicenseUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserLicenseUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  robloxUserId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  accessType?: Prisma.EnumAccessTypeFieldUpdateOperationsInput | $Enums.AccessType
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserLicenseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  robloxUserId?: boolean
  productId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userLicense"]>



export type UserLicenseSelectScalar = {
  id?: boolean
  robloxUserId?: boolean
  productId?: boolean
  accessType?: boolean
  reason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserLicenseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "robloxUserId" | "productId" | "accessType" | "reason" | "createdAt" | "updatedAt", ExtArgs["result"]["userLicense"]>
export type UserLicenseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $UserLicensePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserLicense"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    robloxUserId: bigint
    productId: string
    accessType: $Enums.AccessType
    reason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["userLicense"]>
  composites: {}
}

export type UserLicenseGetPayload<S extends boolean | null | undefined | UserLicenseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserLicensePayload, S>

export type UserLicenseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserLicenseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserLicenseCountAggregateInputType | true
  }

export interface UserLicenseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserLicense'], meta: { name: 'UserLicense' } }
  /**
   * Find zero or one UserLicense that matches the filter.
   * @param {UserLicenseFindUniqueArgs} args - Arguments to find a UserLicense
   * @example
   * // Get one UserLicense
   * const userLicense = await prisma.userLicense.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserLicenseFindUniqueArgs>(args: Prisma.SelectSubset<T, UserLicenseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserLicense that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserLicenseFindUniqueOrThrowArgs} args - Arguments to find a UserLicense
   * @example
   * // Get one UserLicense
   * const userLicense = await prisma.userLicense.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserLicenseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserLicenseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserLicense that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseFindFirstArgs} args - Arguments to find a UserLicense
   * @example
   * // Get one UserLicense
   * const userLicense = await prisma.userLicense.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserLicenseFindFirstArgs>(args?: Prisma.SelectSubset<T, UserLicenseFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserLicense that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseFindFirstOrThrowArgs} args - Arguments to find a UserLicense
   * @example
   * // Get one UserLicense
   * const userLicense = await prisma.userLicense.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserLicenseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserLicenseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserLicenses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserLicenses
   * const userLicenses = await prisma.userLicense.findMany()
   * 
   * // Get first 10 UserLicenses
   * const userLicenses = await prisma.userLicense.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userLicenseWithIdOnly = await prisma.userLicense.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserLicenseFindManyArgs>(args?: Prisma.SelectSubset<T, UserLicenseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserLicense.
   * @param {UserLicenseCreateArgs} args - Arguments to create a UserLicense.
   * @example
   * // Create one UserLicense
   * const UserLicense = await prisma.userLicense.create({
   *   data: {
   *     // ... data to create a UserLicense
   *   }
   * })
   * 
   */
  create<T extends UserLicenseCreateArgs>(args: Prisma.SelectSubset<T, UserLicenseCreateArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserLicenses.
   * @param {UserLicenseCreateManyArgs} args - Arguments to create many UserLicenses.
   * @example
   * // Create many UserLicenses
   * const userLicense = await prisma.userLicense.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserLicenseCreateManyArgs>(args?: Prisma.SelectSubset<T, UserLicenseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a UserLicense.
   * @param {UserLicenseDeleteArgs} args - Arguments to delete one UserLicense.
   * @example
   * // Delete one UserLicense
   * const UserLicense = await prisma.userLicense.delete({
   *   where: {
   *     // ... filter to delete one UserLicense
   *   }
   * })
   * 
   */
  delete<T extends UserLicenseDeleteArgs>(args: Prisma.SelectSubset<T, UserLicenseDeleteArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserLicense.
   * @param {UserLicenseUpdateArgs} args - Arguments to update one UserLicense.
   * @example
   * // Update one UserLicense
   * const userLicense = await prisma.userLicense.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserLicenseUpdateArgs>(args: Prisma.SelectSubset<T, UserLicenseUpdateArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserLicenses.
   * @param {UserLicenseDeleteManyArgs} args - Arguments to filter UserLicenses to delete.
   * @example
   * // Delete a few UserLicenses
   * const { count } = await prisma.userLicense.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserLicenseDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserLicenseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserLicenses
   * const userLicense = await prisma.userLicense.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserLicenseUpdateManyArgs>(args: Prisma.SelectSubset<T, UserLicenseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one UserLicense.
   * @param {UserLicenseUpsertArgs} args - Arguments to update or create a UserLicense.
   * @example
   * // Update or create a UserLicense
   * const userLicense = await prisma.userLicense.upsert({
   *   create: {
   *     // ... data to create a UserLicense
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserLicense we want to update
   *   }
   * })
   */
  upsert<T extends UserLicenseUpsertArgs>(args: Prisma.SelectSubset<T, UserLicenseUpsertArgs<ExtArgs>>): Prisma.Prisma__UserLicenseClient<runtime.Types.Result.GetResult<Prisma.$UserLicensePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseCountArgs} args - Arguments to filter UserLicenses to count.
   * @example
   * // Count the number of UserLicenses
   * const count = await prisma.userLicense.count({
   *   where: {
   *     // ... the filter for the UserLicenses we want to count
   *   }
   * })
  **/
  count<T extends UserLicenseCountArgs>(
    args?: Prisma.Subset<T, UserLicenseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserLicenseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserLicenseAggregateArgs>(args: Prisma.Subset<T, UserLicenseAggregateArgs>): Prisma.PrismaPromise<GetUserLicenseAggregateType<T>>

  /**
   * Group by UserLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserLicenseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserLicenseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserLicenseGroupByArgs['orderBy'] }
      : { orderBy?: UserLicenseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserLicenseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserLicenseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserLicense model
 */
readonly fields: UserLicenseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserLicense.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserLicenseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserLicense model
 */
export interface UserLicenseFieldRefs {
  readonly id: Prisma.FieldRef<"UserLicense", 'String'>
  readonly robloxUserId: Prisma.FieldRef<"UserLicense", 'BigInt'>
  readonly productId: Prisma.FieldRef<"UserLicense", 'String'>
  readonly accessType: Prisma.FieldRef<"UserLicense", 'AccessType'>
  readonly reason: Prisma.FieldRef<"UserLicense", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserLicense", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UserLicense", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserLicense findUnique
 */
export type UserLicenseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * Filter, which UserLicense to fetch.
   */
  where: Prisma.UserLicenseWhereUniqueInput
}

/**
 * UserLicense findUniqueOrThrow
 */
export type UserLicenseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * Filter, which UserLicense to fetch.
   */
  where: Prisma.UserLicenseWhereUniqueInput
}

/**
 * UserLicense findFirst
 */
export type UserLicenseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * Filter, which UserLicense to fetch.
   */
  where?: Prisma.UserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserLicenses to fetch.
   */
  orderBy?: Prisma.UserLicenseOrderByWithRelationInput | Prisma.UserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserLicenses.
   */
  cursor?: Prisma.UserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserLicenses.
   */
  distinct?: Prisma.UserLicenseScalarFieldEnum | Prisma.UserLicenseScalarFieldEnum[]
}

/**
 * UserLicense findFirstOrThrow
 */
export type UserLicenseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * Filter, which UserLicense to fetch.
   */
  where?: Prisma.UserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserLicenses to fetch.
   */
  orderBy?: Prisma.UserLicenseOrderByWithRelationInput | Prisma.UserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserLicenses.
   */
  cursor?: Prisma.UserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserLicenses.
   */
  distinct?: Prisma.UserLicenseScalarFieldEnum | Prisma.UserLicenseScalarFieldEnum[]
}

/**
 * UserLicense findMany
 */
export type UserLicenseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * Filter, which UserLicenses to fetch.
   */
  where?: Prisma.UserLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserLicenses to fetch.
   */
  orderBy?: Prisma.UserLicenseOrderByWithRelationInput | Prisma.UserLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserLicenses.
   */
  cursor?: Prisma.UserLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserLicenses.
   */
  distinct?: Prisma.UserLicenseScalarFieldEnum | Prisma.UserLicenseScalarFieldEnum[]
}

/**
 * UserLicense create
 */
export type UserLicenseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * The data needed to create a UserLicense.
   */
  data: Prisma.XOR<Prisma.UserLicenseCreateInput, Prisma.UserLicenseUncheckedCreateInput>
}

/**
 * UserLicense createMany
 */
export type UserLicenseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserLicenses.
   */
  data: Prisma.UserLicenseCreateManyInput | Prisma.UserLicenseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserLicense update
 */
export type UserLicenseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * The data needed to update a UserLicense.
   */
  data: Prisma.XOR<Prisma.UserLicenseUpdateInput, Prisma.UserLicenseUncheckedUpdateInput>
  /**
   * Choose, which UserLicense to update.
   */
  where: Prisma.UserLicenseWhereUniqueInput
}

/**
 * UserLicense updateMany
 */
export type UserLicenseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserLicenses.
   */
  data: Prisma.XOR<Prisma.UserLicenseUpdateManyMutationInput, Prisma.UserLicenseUncheckedUpdateManyInput>
  /**
   * Filter which UserLicenses to update
   */
  where?: Prisma.UserLicenseWhereInput
  /**
   * Limit how many UserLicenses to update.
   */
  limit?: number
}

/**
 * UserLicense upsert
 */
export type UserLicenseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * The filter to search for the UserLicense to update in case it exists.
   */
  where: Prisma.UserLicenseWhereUniqueInput
  /**
   * In case the UserLicense found by the `where` argument doesn't exist, create a new UserLicense with this data.
   */
  create: Prisma.XOR<Prisma.UserLicenseCreateInput, Prisma.UserLicenseUncheckedCreateInput>
  /**
   * In case the UserLicense was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserLicenseUpdateInput, Prisma.UserLicenseUncheckedUpdateInput>
}

/**
 * UserLicense delete
 */
export type UserLicenseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
  /**
   * Filter which UserLicense to delete.
   */
  where: Prisma.UserLicenseWhereUniqueInput
}

/**
 * UserLicense deleteMany
 */
export type UserLicenseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserLicenses to delete
   */
  where?: Prisma.UserLicenseWhereInput
  /**
   * Limit how many UserLicenses to delete.
   */
  limit?: number
}

/**
 * UserLicense without action
 */
export type UserLicenseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserLicense
   */
  select?: Prisma.UserLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserLicense
   */
  omit?: Prisma.UserLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserLicenseInclude<ExtArgs> | null
}
